server:
  servlet:
    context-path: /api
  port: 8079

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/coursemanagement
    username: postgres
    password: password
    pool-size: 30